### ISSUE TITLE
Display total and remaining duration of test

### ISSUE THREAD

**Issue by KennethHoff** [szkiba/xk6-top#2]
Hey, I just tried it and it looks really nice. I have one problem though, it doesn't seem to show how long the test has been running for (and/or remaining duration).

Additionally, would it be possible to show the name of the currently-running script?

**Comment by szkiba** [comment]
Hi @KennethHoff , thank you your suggestions.
Displaying remaining time is a bit tricky. My original plan was to display it, in a form of progress bar, but I had some difficulty calculating whole test run duration. It is related to scenarios and ramp up/down periods. This is why I currently not show the progress bar at all. I'll try to figure out how to calculate exact duration and then show the progress bar.
Displaying the current script could cost some space on screen and usually the windowing system already show the command line. Yes, maybe you run k6 from a batch file/script, in this case it would be helpful. I'll consider it...

**Comment by szkiba** [comment]
Hi @KennethHoff ,  In the meantime, v0.2.0 was released, which now displays the test run time (and progress bar).
The script name is also planned to be displayed.
